"""create events reminders recurring_expenses

Revision ID: d0a81bd19d00
Revises: 0001_baseline
Create Date: 2026-09-27 22:09:55.585208

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd0a81bd19d00'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('recurrence', sa.Enum('none', 'yearly', name='eventrecurrence', native_enum=False), nullable=False),
    sa.Column('action_text', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("recurrence IN ('none', 'yearly')", name='ck_events_recurrence'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_next_date'), ['next_date'], unique=False)

    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period', sa.Enum('monthly', 'quarterly', 'yearly', name='expenseperiod', native_enum=False), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("currency <> ''", name='ck_recurring_expenses_currency_nonempty'),
    sa.CheckConstraint("period IN ('monthly', 'quarterly', 'yearly')", name='ck_recurring_expenses_period'),
    sa.CheckConstraint('amount_minor > 0', name='ck_recurring_expenses_amount_positive'),
    sa.CheckConstraint('payment_day BETWEEN 1 AND 31', name='ck_recurring_expenses_payment_day'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_expenses_next_payment_date'), ['next_payment_date'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.Date(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_remind_at'), ['remind_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_remind_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_event_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_expenses_next_payment_date'))

    op.drop_table('recurring_expenses')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_next_date'))

    op.drop_table('events')
    # ### end Alembic commands ###
